# Developer: Maik Ellerbrock <opensource@frapsoft.com>
#
# GitHub:  https://github.com/ellerbrock
# Twitter: https://twitter.com/frapsoft
# Docker:  https://hub.docker.com/u/ellerbrock
# Quay:    https://quay.io/user/ellerbrock

version: "2"

services:
  alpine-cloudflare-dyndns:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_USER: ${SERVICE_USER}
        SERVICE_HOME: ${SERVICE_HOME}
        SYSTEM_TZ: ${SYSTEM_TZ}
        EXTERNAL_IP: ${EXTERNAL_IP}
        CF_EMAIL: ${CF_EMAIL}
        CF_TOKEN: ${CF_TOKEN}
        CF_ZONE_NAME: ${CF_ZONE_NAME}
        CF_DOMAIN_NAME: ${CF_DOMAIN_NAME}

